name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2 Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3 Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4 Make src available as module
      - name: Make src available as module
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # 5 Create tiny model for CI
      - name: Create tiny model for CI
        run: python scripts/create_tiny_model.py


      # 6 Upload local_model as artifact
      - name: Upload local_model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: local_model
          path: local_model/

      # 7 Run tests
      - name: Run tests
        run: pytest -v
