name: CI/CD Pipeline

on: # triggers workflow on push or PR to main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test: # defines a job called 'build-and-test' that runs on ubuntu
    runs-on: ubuntu-latest

    steps:
      # step 1: checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # step 2: set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # step 3: install dependencies (create virtual env and installs packages)
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # step 4: run unit tests
      - name: Run unit tests # runs pytest to ensure the API and prediction function work
        run: |
          source .venv/bin/activate
          export PYTHONPATH="$PYTHONPATH:$(pwd)"
          pytest -q 

      # step 5: run training script
      - name: Run training pipeline
        run: |
          source .venv/bin/activate
          python src/train.py
